### ISSUE TITLE
Express.ts

### ISSUE THREAD

**Issue by adimchi1** [joec05/social-media-app-pgsql#1]
Hello, this project looks fantastic! I'm attempting to replicate it, but it appears that the repository is missing the "express.ts" file

**Comment by joec05** [comment]
I think I forgot to set the repository to public. I can just do that now and make some changes to the README, however there's a bunch of sensitive data right there and a lot of boilerplates so it might take some time to get that fixed. I'll notify you after I finished this.

**Comment by joec05** [comment]
Okay, I'm finished with this. You can view it [here](https://github.com/joec05/social-media-app-expressjs-server). Remember to set up a proper PostgreSQL environment and set up the user, password, username, IP, etc. I kept those sections empty for privacy reasons.

**Comment by adimchi1** [comment]
ok, thanks so much
